SELECT I.ITEM_ID, I.ITEM_NAME 
FROM ITEM_INFO I JOIN ITEM_TREE T USING(ITEM_ID)
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID ASC;

-- A -> B와 같이 업그레이드가 가능할 때
-- A를 B의 PARENT 아이템
-- PARENT 아이템이 없는 아이템을 ROOT 아이템
-- ROOT 아이템의 PARENT 아이템 ID는 NULL