SELECT CAR_ID,
        ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

-- 평균 대여 기간을 기준으로 내림차순 정렬해주시고,
-- 평균 대여 기간이 같으면 자동차 ID를 기준으로 내림차순 정렬