SELECT 
    CONCAT(QUARTER(DIFFERENTIATION_DATE) , 'Q') AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA 
GROUP BY QUARTER
ORDER BY QUARTER ASC;

-- 최초의 대장균 개체의 PARENT_ID 는 NULL 
-- 각 분기(QUARTER)별 분화된 대장균의 개체의 총 수(ECOLI_COUNT)를 출력하는 SQL 문