SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM SKILLCODES S JOIN DEVELOPERS D
        ON (S.CODE & D.SKILL_CODE) > 0
WHERE S.NAME = 'C#' OR S.NAME = 'PYTHON'
ORDER BY D.ID ASC;

-- SKILLCODES (NAME, CATEGORY, CODE)
-- DEVELOPERS (ID, FIRST_NAME(이름), LAST_NAME(성), EMAIL, SKILL_CODE)
-- DEVELOPERS 테이블에서 Python이나 C# 스킬을 가진 개발자의 정보
-- PYTOHN 256, C# 1024