SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F JOIN ICECREAM_INFO I
        USING(FLAVOR)
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;

-- 아이스크림 가게의 상반기 주문 정보를 담은 FIRST_HALF 테이블
-- 아이스크림 성분에 대한 정보를 담은 ICECREAM_INFO 테이블
-- ICECREAM_INFO의 FLAVOR는 FIRST_HALF 테이블의 FLAVOR의 외래 키
-- 총주문량을 나타내는 컬럼명은 TOTAL_ORDER로 지정