SELECT  FLOOR(PRICE / 10000) * 10000 AS PRICE_GROUP
        , COUNT(PRODUCT_CODE) AS PRODUCTS
FROM PRODUCT
GROUP BY FLOOR(PRICE / 10000) * 10000
ORDER BY PRICE_GROUP ASC;

-- 만원 단위의 가격대 별로 상품 개수를 출력하는 SQL 문을 작성
-- 결과는 가격대를 기준으로 오름차순 정렬